OMAP4: PRM: fix build breakage when CONFIG_OF is not defined
Since 3.3-rc1, prm44xx.c build breaks if CONFIG_OF is not set:

arch/arm/mach-omap2/prm44xx.c:41: error: 'OMAP44XX_IRQ_PRCM' undeclared here (not in a function)
make[1]: *** [arch/arm/mach-omap2/prm44xx.o] Error 1

This is because of a missing include, which is added indirectly if
CONFIG_OF is defined.  This problem was introduced in commit
2f31b51 (ARM: OMAP4: PRM: use PRCM interrupt handler).

Cc: Tero Kristo <t-kristo@ti.com>
Signed-off-by: Luciano Coelho <coelho@ti.com>
Reviewed-by: Felipe Balbi <balbi@ti.com>